


export const departamentosColombia = [
    {"name":"Amazonas",       "id": 1},
    {"name":"Antioquia",      "id": 2},
    {"name":"Arauca",         "id": 3},
    {"name":"Atlántico",      "id": 4},
    {"name":"Bogotá",         "id": 5},
    {"name":"Bolivar",         "id": 6},
    {"name":"Boyacá",         "id": 7},
    {"name":"Caldas",         "id": 8},
    {"name":"Caquetá",        "id": 9},
    {"name":"Casanare",       "id": 10},
    {"name":"Cauca",          "id": 11},
    {"name":"Cesar",          "id": 12},
    {"name":"Chocó",          "id": 13},
    {"name":"Córdoba",        "id": 14},
    {"name":"Cundinamarca", "id": 15},
    {"name":"Guainía", "id": 16},
    {"name":"Guaviare", "id": 17},
    {"name":"Huila", "id": 18},
    {"name":"La Guajira", "id": 19},
    {"name":"Magdalena", "id": 20},
    {"name":"Meta", "id": 21},
    {"name":"Nariño", "id": 22},
    {"name":"Norte de Santander", "id": 23},
    {"name":"Putumayo", "id": 24},
    {"name":"Quindío", "id": 25},
    {"name":"Risaralda", "id": 26},
    {"name":"San Andrés yProvidencia", "id": 27 },
    {"name":"Santander", "id": 28},
    {"name":"Sucre", "id": 29},
    {"name":"Tolima", "id": 30},
    {"name":"Valle del Cauca", "id": 31},
    {"name":"Vaupés", "id": 32},
    {"name":"Vichada", "id": 33},
  ];